User.create(:id => 1, :email => "pitosalas@gmail.com", :name => "Pito Salas", :password => "daniel", :sign_in_count => 0, :roles_mask => 4)
User.create(:id => 58, :email => "abe@gmail.com", :name => "Abe", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 59, :email => "bert@gmail.com", :name => "Bert", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 60, :email => "chris@gmail.com", :name => "Chris", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 61, :email => "dan@gmail.com", :name => "Dan", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 62, :email => "eric@gmail.com", :name => "Eric", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 63, :email => "fanny@gmail.com", :name => "Fanny", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 64, :email => "gina@gmail.com", :name => "Gina", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 65, :email => "hal@gmail.com", :name => "Hal", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 66, :email => "igor@gmail.com", :name => "Igor", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 67, :email => "jackie@gmail.com", :name => "Jakie", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 68, :email => "ken@gmail.com", :name => "Ken", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
User.create(:id => 69, :email => "larry@gmail.com", :name => "Larry", :password => "daniel", :sign_in_count => 0, :roles_mask => 1)
