Question.create(:id => 46, :text => "Scalability vs Performance", :pos => 56, :program_id => 6)
Question.create(:id => 47, :text => "Ruby Programming", :pos => 9, :program_id => 6)
Question.create(:id => 48, :text => "Ruby on Rails", :pos => 10, :program_id => 6)
Question.create(:id => 49, :text => "Unit tests (Rspec)", :pos => 11, :program_id => 6)
Question.create(:id => 50, :text => "Paper Prototyping", :pos => 12, :program_id => 6)
Question.create(:id => 51, :text => "Rails Models", :pos => 13, :program_id => 6)
Question.create(:id => 52, :text => "Rails Controllers", :pos => 14, :program_id => 6)
Question.create(:id => 53, :text => "Rails Views", :pos => 15, :program_id => 6)
Question.create(:id => 54, :text => "Model/View/Contoller", :pos => 16, :program_id => 6)
Question.create(:id => 55, :text => "Scrum and/or agile", :pos => 17, :program_id => 6)
Question.create(:id => 56, :text => "REST", :pos => 18, :program_id => 6)
Question.create(:id => 57, :text => "HTML and CSS", :pos => 19, :program_id => 6)
Question.create(:id => 58, :text => "Javascript", :pos => 20, :program_id => 6)
Question.create(:id => 59, :text => "Designing Data Models", :pos => 21, :program_id => 6)
Question.create(:id => 60, :text => "Internet architecture/TCP/IP etc", :pos => 22, :program_id => 6)
Question.create(:id => 61, :text => "Lean Startup", :pos => 23, :program_id => 6)
Question.create(:id => 62, :text => "Viral growth for social networks", :pos => 24, :program_id => 6)
Question.create(:id => 63, :text => "Mobile App Architectures", :pos => 25, :program_id => 6)
Question.create(:id => 64, :text => "Writing Scrum Stories", :pos => 26, :program_id => 6)
Question.create(:id => 65, :text => "How to do login and authentication in a web app", :pos => 27, :program_id => 6)
Question.create(:id => 66, :text => "Databases and migrations", :pos => 28, :program_id => 6)
Question.create(:id => 67, :text => "Scaling web based applications", :pos => 29, :program_id => 6)
Question.create(:id => 68, :text => "Regular Expressions", :pos => 31, :program_id => 6)
Question.create(:id => 69, :text => "Duck Typing in Ruby", :pos => 32, :program_id => 6)
Question.create(:id => 70, :text => "Conducting effective usability tests", :pos => 33, :program_id => 6)
Question.create(:id => 71, :text => "One to one, one to many, many to one data models", :pos => 34, :program_id => 6)
Question.create(:id => 72, :text => "HTTP, stateless protocols, GET, PUT, POST, etc.", :pos => 35, :program_id => 6)
Question.create(:id => 73, :text => "Object Oriented Design", :pos => 36, :program_id => 6)
Question.create(:id => 74, :text => "Elevator Pitch", :pos => 37, :program_id => 6)
Question.create(:id => 75, :text => "Relational Database", :pos => 39, :program_id => 6)
Question.create(:id => 76, :text => "NOSQL database", :pos => 40, :program_id => 6)
Question.create(:id => 77, :text => "SQL: Structured Query Language", :pos => 41, :program_id => 6)
Question.create(:id => 78, :text => "Structure a relational database for a Many-to-Many relationship", :pos => 42, :program_id => 6)
Question.create(:id => 79, :text => "Cohort Analysis: how do do it, what it means", :pos => 43, :program_id => 6)
Question.create(:id => 80, :text => "Visual Design for User Interface", :pos => 45, :program_id => 6)
Question.create(:id => 81, :text => "How to criticality assess usability of a user interface", :pos => 46, :program_id => 6)
Question.create(:id => 82, :text => "Affordances (as used in design)", :pos => 47, :program_id => 6)
Question.create(:id => 83, :text => "How to run a meeting", :pos => 48, :program_id => 6)
Question.create(:id => 84, :text => "How to manage a business relationship with another organization", :pos => 49, :program_id => 6)
Question.create(:id => 85, :text => "How to work productively in a small team", :pos => 50, :program_id => 6)
Question.create(:id => 86, :text => "How to lead a small team", :pos => 51, :program_id => 6)
Question.create(:id => 87, :text => "Developing and deploying a mobile application", :pos => 52, :program_id => 6)
Question.create(:id => 88, :text => "Basics of startup finance", :pos => 53, :program_id => 6)
Question.create(:id => 89, :text => "3-Tier architectures", :pos => 54, :program_id => 6)
Question.create(:id => 90, :text => "Scaling Up vs. Scaling Out", :pos => 55, :program_id => 6)
